categories:
  - title: '🏢 Backend'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'misc'
      - 'chore'
      - 'typo'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What’s Changed

  $CHANGES
